modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/noobanidus/carrierbees/issues" #optional
license="https://github.com/noobanidus/carrier-bees/blob/master/LICENSE"
[[mods]] #mandatory
modId="carrierbees" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Carrier Bees" #mandatory
displayURL="https://minecraft.curseforge.com/projects/carrier-bees" #optional
logoFile="logo.png" #optional
authors="Noobanidus"
description='''
Bees that carry things.
'''
[[dependencies.CarrierBees]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.CarrierBees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
